var TREE_ITEMS = [ 
	['US Government Supplier Shipping', './SupplierShippingv2.htm', 
		['Label Definitions', './SupplierShippingv2.htm#LabelDef',
			['Unit Label', './SupplierShippingv2.htm#UnitLabel', ],
			['External Label', './SupplierShippingv2.htm#ExternalLabel', ],
			['RFID Case Label','./SupplierShippingv2.htm#RFIDCaseLabel', ],
			['RFID Pallet Label','./SupplierShippingv2.htm#RFIDPalletLabel', ],
			['Military Shipping Label','./SupplierShippingv2.htm#MSL', ],
		],
		['Supplier Shipping Home', './SupplierShippingv2.htm#Home',],
		['Shipment Selection', './SupplierShippingv2.htm#ShipmentSelection',],
		['Labeling', './SupplierShippingv2.htm#Labeling',],
		['Scanning', './SupplierShippingv2.htm#Scanning',
			['Case Association', './SupplierShippingv2.htm#CaseAssociation', ],
			['Viewing Case Contents', './SupplierShippingv2.htm#ViewCaseContents', ],
			['Adding Tracking Data', './SupplierShippingv2.htm#AddTrackingData', ],
			['Switching to Pallet Association Mode', './SupplierShippingv2.htm#SwitchToPalletAssociation', ],
			['Viewing Pallet Contents', './SupplierShippingv2.htm#ViewPalletContents', ],
			['Adding Tracking Data', './SupplierShippingv2.htm#AddTrackingData', ],
			['Switching to Case Association Mode', './SupplierShippingv2.htm#SwitchToCaseAssociation', ],
			['File Transfer', './SupplierShippingv2.htm#FileTransfer', ],
			['Clearing the Scanner', './SupplierShippingv2.htm#ClearingScanner', ],
			['Updating the Scanner', './SupplierShippingv2.htm#UpdateScanner', ],
		],
		['Scanner Upload', './SupplierShippingv2.htm#ScannerUpload',],
		['Pack and Confirm', './SupplierShippingv2.htm#ScannerUpload',],
		['Examples', './SupplierShippingv2.htm#Examples',	],
	],	
];
