var TREE_ITEMS = [ 
	['tcmIS User Guide', './FECtcmISUserGuidev1.htm', 
		['Installation', './FECtcmISUserGuidev1.htm#install'],
		['Chemicals and Cylinder Gasses', './FECtcmISUserGuidev1.htm#Chemicals', 
			['Chemical and Gas Catalog', './FECtcmISUserGuidev1.htm#chemcat', 
				['Part Catalog','./FECtcmISUserGuidev1.htm#partcat'],
				['Item Catalog', './FECtcmISUserGuidev1.htm#itemcat'],
			],
			['Chemical and Gas Order Tracking', './FECtcmISUserGuidev1.htm#tracking',
				['Searching','./FECtcmISUserGuidev1.htm#limit'],
				['Order Status', './FECtcmISUserGuidev1.htm#status'],
			],
			['Inventory Status', './FECtcmISUserGuidev1.htm#inv'],
			['Catalog Additions', './FECtcmISUserGuidev1.htm#catadd'],
			['Catalog Addition Tracking', './FECtcmISUserGuidev1.htm#cataddtrack'],
		], 
		['Reports', './FECtcmISUserGuidev1.htm#reports',
				['Formatted Usage', './FECtcmISUserGuidev1.htm#formattedusage'],
				['Formatted VOC Usage', './FECtcmISUserGuidev1.htm#formattedvocusage'],
				['Formatted MSDS', './FECtcmISUserGuidev1.htm#formattedmsds'],
				['Ad Hoc Usage', './FECtcmISUserGuidev1.htm#adhocusage'],
				['Ad Hoc Material Matrix', './FECtcmISUserGuidev1.htm#matrix'],
		], 
		['Change User Profile', './FECtcmISUserGuidev1.htm#users'],
		['Cost Report', './FECtcmISUserGuidev1.htm#costreport'],
	],
];
