var TREE_ITEMS = [ 
	['tcmIS User Guide', './DANAtcmISUserGuidev1.htm', 
		['Installation', './DANAtcmISUserGuidev1.htm#install'],
		['Chemicals and Cylinder Gasses', './DANAtcmISUserGuidev1.htm#Chemicals', 
			['Chemical and Gas Catalog', './DANAtcmISUserGuidev1.htm#chemcat', 
				['Part Catalog','./DANAtcmISUserGuidev1.htm#partcat'],
				['Item Catalog', './DANAtcmISUserGuidev1.htm#itemcat'],
			],
			['Chemical and Gas Order Placement', './DANAtcmISUserGuidev1.htm#order',
				['Delivery Scheduling','./DANAtcmISUserGuidev1.htm#schedule'],
				['Charge Number Entry', './DANAtcmISUserGuidev1.htm#charge'],
				['Order Submission', './DANAtcmISUserGuidev1.htm#submit'],
			],
			['Chemical and Gas Order Tracking', './DANAtcmISUserGuidev1.htm#tracking',
				['Searching','./DANAtcmISUserGuidev1.htm#limit'],
				['Order Status', './DANAtcmISUserGuidev1.htm#status'],
			],
			['Inventory Status', './DANAtcmISUserGuidev1.htm#inv'],
			['Catalog Additions', './DANAtcmISUserGuidev1.htm#catadd'],
			['Catalog Addition Tracking', './DANAtcmISUserGuidev1.htm#cataddtrack'],
		], 
		['Waste', './DANAtcmISUserGuidev1.htm#waste',
			['Waste Catalog', './DANAtcmISUserGuidev1.htm#wastecatalog'],
			['Waste Management Request', './DANAtcmISUserGuidev1.htm#WMRequest'],
			['Waste Transfer Management', './DANAtcmISUserGuidev1.htm#transfer'], 
			['Waste Storage Management', './DANAtcmISUserGuidev1.htm#storage',
				['Accumulation Container', './DANAtcmISUserGuidev1.htm#accum'],
				['Waste Travelers', './DANAtcmISUserGuidev1.htm#traveler'],
				['Ordering a Waste Pickup', './DANAtcmISUserGuidev1.htm#placeorder'],   
			], 
			['Waste Orders', './DANAtcmISUserGuidev1.htm#vendor',
				['Order Submission', './DANAtcmISUserGuidev1.htm#submitwaste'],
				['Ordering Waste Materials', './DANAtcmISUserGuidev1.htm#materials'], 
				['Entering Weights', './DANAtcmISUserGuidev1.htm#weights'],   
				['Entering Lab Pack Containers', './DANAtcmISUserGuidev1.htm#labpack'],
				['Editing Shipment Information', './DANAtcmISUserGuidev1.htm#shipment'],  
				['Bulk Waste', './DANAtcmISUserGuidev1.htm#bulk'], 
				['Viewing Shipment Costs', './DANAtcmISUserGuidev1.htm#costs'],   
				['Viewing the Vendor Invoice', './DANAtcmISUserGuidev1.htm#vendorinvoice'],  
			],
			['Waste Order Tracking', './DANAtcmISUserGuidev1.htm#shipping'],
		], 
		['Reports', './DANAtcmISUserGuidev1.htm#reports',
				['Formatted Usage', './DANAtcmISUserGuidev1.htm#formattedusage'],
				['Formatted VOC Usage', './DANAtcmISUserGuidev1.htm#formattedvocusage'],
				['Formatted MSDS', './DANAtcmISUserGuidev1.htm#formattedmsds'],
				['Ad Hoc Usage', './DANAtcmISUserGuidev1.htm#adhocusage'],
				['Ad Hoc Material Matrix', './DANAtcmISUserGuidev1.htm#matrix'],
				['Ad Hoc Waste', './DANAtcmISUserGuidev1.htm#adhocwaste'],
		], 
		['Change User Profile', './DANAtcmISUserGuidev1.htm#users'],
		['Cost Report', './DANAtcmISUserGuidev1.htm#costreport'],
	],
];
