var TREE_ITEMS = [ 
	['tcmIS User Guide', './TCMISDOCUMENTATIONV2.0.html', 
		['Installation', './TCMISDOCUMENTATIONV2.0.html#install'],
		['Chemicals and Cylinder Gasses', './TCMISDOCUMENTATIONV2.0.html#Chemicals', 
			['Chemical and Gas Catalog', './TCMISDOCUMENTATIONV2.0.html#chemcat', 
				['Part Catalog','./TCMISDOCUMENTATIONV2.0.html#partcat'],
				['Item Catalog', './TCMISDOCUMENTATIONV2.0.html#itemcat'],
			],
			['Chemical and Gas Order Placement', './TCMISDOCUMENTATIONV2.0.html#order',
				['Delivery Scheduling','./TCMISDOCUMENTATIONV2.0.html#schedule'],
				['Charge Number Entry', './TCMISDOCUMENTATIONV2.0.html#charge'],
				['Order Submission', './TCMISDOCUMENTATIONV2.0.html#submit'],
			],
			['Chemical and Gas Order Tracking', './TCMISDOCUMENTATIONV2.0.html#tracking',
				['Searching','./TCMISDOCUMENTATIONV2.0.html#limit'],
				['Order Status', './TCMISDOCUMENTATIONV2.0.html#status'],
			],
			['Inventory Status', './TCMISDOCUMENTATIONV2.0.html#inv'],
			['Catalog Additions', './TCMISDOCUMENTATIONV2.0.html#catadd'],
			['Catalog Addition Tracking', './TCMISDOCUMENTATIONV2.0.html#cataddtrack'],
			['Engineering Evaluations', './TCMISDOCUMENTATIONV2.0.html#eval'],
		], 
		['Waste', './TCMISDOCUMENTATIONV2.0.html#waste',
			['Waste Catalog', './TCMISDOCUMENTATIONV2.0.html#wastecatalog'],
			['Waste Management Request', './TCMISDOCUMENTATIONV2.0.html#WMRequest'],
			['Waste Transfer Management', './TCMISDOCUMENTATIONV2.0.html#transfer'], 
			['Waste Storage Management', './TCMISDOCUMENTATIONV2.0.html#storage',
				['Accumulation Container', './TCMISDOCUMENTATIONV2.0.html#accum'],
				['Waste Travelers', './TCMISDOCUMENTATIONV2.0.html#traveler'],
				['Ordering a Waste Pickup', './TCMISDOCUMENTATIONV2.0.html#placeorder'],   
			], 
			['Waste Orders', './TCMISDOCUMENTATIONV2.0.html#vendor',
				['Order Submission', './TCMISDOCUMENTATIONV2.0.html#submitwaste'],
				['Ordering Waste Materials', './TCMISDOCUMENTATIONV2.0.html#materials'], 
				['Entering Weights', './TCMISDOCUMENTATIONV2.0.html#weights'],   
				['Entering Lab Pack Containers', './TCMISDOCUMENTATIONV2.0.html#labpack'],
				['Editing Shipment Information', './TCMISDOCUMENTATIONV2.0.html#shipment'],  
				['Bulk Waste', './TCMISDOCUMENTATIONV2.0.html#bulk'], 
				['Viewing Shipment Costs', './TCMISDOCUMENTATIONV2.0.html#costs'],   
				['Viewing the Vendor Invoice', './TCMISDOCUMENTATIONV2.0.html#vendorinvoice'],  
			],
			['Waste Order Tracking', './TCMISDOCUMENTATIONV2.0.html#shipping'],
		], 
		['Reports', './TCMISDOCUMENTATIONV2.0.html#reports',
				['Formatted Usage', './TCMISDOCUMENTATIONV2.0.html#formattedusage'],
				['Formatted VOC Usage', './TCMISDOCUMENTATIONV2.0.html#formattedvocusage'],
				['Formatted MSDS', './TCMISDOCUMENTATIONV2.0.html#formattedmsds'],
				['Ad Hoc Usage', './TCMISDOCUMENTATIONV2.0.html#adhocusage'],
				['Ad Hoc Material Matrix', './TCMISDOCUMENTATIONV2.0.html#matrix'],
				['Ad Hoc Waste', './TCMISDOCUMENTATIONV2.0.html#adhocwaste'],
		], 
		['Change User Profile', './TCMISDOCUMENTATIONV2.0.html#users'], 
		['FAQ',null,
			['What is this?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1000'], 
			['How are MinMax setpoints determined?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1007'],
			['How do exitMM items work?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1006'],
			['How are items set up and determined as MinMax (MM)?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1003'],
			['How and why are items changed to exitMM?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1005'],
			['How are scheduled deliveries (SCH) handled?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1008'],
			['How are minimum buys processed?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1009'],
			['What are potential fees in addition to product costs?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1010'],
			['How are additional fees allocated and charged?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1011'],
			['How is obsolete material determined and processed?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1012'],
			['How does inventory become customer-owned stock?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1024'],
			['What is Slow Moving Material and how is it processed?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1014'],
			['What is Expired Product and how is it processed?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1015'],
			['How do I receive tcmIS training?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1016'],
			['How can I obtain chemical usage reports or other environmental reports?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1017'],
			['How can I contact Haas TCM or coworkers using tcmIS?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1018'],
			['How can I get technical assistance, for example inventory planning assistance?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1019'],
			['How can I let my Haas TCM representative know about changes in my chemical forecasts?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1020'],
			['How can I find out about the hazardous waste processes on tcmIS?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1021'],
			['How are incoming materials inspected? What about recertifications for materials?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1022'],
			['How do I find out about the status of my order?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1023'],
			['Are there any fees for stocking customer-owned stock at the Haas TCM hub?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1026'],
			['When someone orders customer-owned material being stocked at the hub, are they charged for the material?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1025'],
			['Why do I get a blank screen when trying to access an MSDS?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1002'],
			['What is customer-owned stock and how does it work?', 'https://www.tcmis.com/tcmIS/servlet/radian.web.servlets.help.SeagatehelpMenu?SessionID=20&qid=1013'],
		],	
	],
];
